### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by m4nch0t** [sexibytes/packer-sexigraf#1]
Hi,
Debian 8 will be soon EOL and in some case such distribution could not be "corporate". Have you ever think of automation with Ansible or an alternative instead of shell scripting?
Pretty sure you could gain visibility and running instances.

in any case, well done

**Comment by rschitz** [comment]
Hi, Next release will be Ubuntu 16.04 LTS and we're using packer now to create the ova template.
Thanks for you support.
